### ISSUE TITLE
CMSSW_10_6_28 (29?) for all UL

### ISSUE THREAD

**Issue by reimersa** [LEAF-HQ/LEAF#7]
Use CMSSW_10_6_28 (or _29?) for all UL generation, tuplization, analysis to conform with PPD recommendations. Generating in this format will automatically correspond to MiniAODv2 if I understood correctly. 
Current 10_6_12 tuples should continue working with Analyzer, since nothing will change in the LEAF-tuple format.

To be done:
- [x] change setup script and all occurrences of this CMSSW version in the configs and code

**Comment by reimersa** [comment]
https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun2LegacyAnalysis

**Comment by anmalara** [comment]
Changed scripts

**Comment by reimersa** [comment]
addressed in #10
